version: '3'

services:
  fhir:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 3000
      MONGO_HOSTNAME: mongo
      RESOURCE_SERVER: http://localhost:3000
      AUTH_SERVER_URI: 
      AUTH_SERVER_AUTHORIZE_URL: https://accounts.google.com/o/oauth2/v2/auth
      AUTH_SERVER_TOKEN_URL: https://www.googleapis.com/oauth2/v4/token
      CLIENT_ID: 236509043190-8b5ii959jd3pspnn5rb8na92pmgfq7dv.apps.googleusercontent.com
      CLIENT_SECRET: xW69SP2pOnrZmXESsop4lWAx
      INTROSPECTION_URL: https://www.googleapis.com/oauth2/v3/tokeninfo
      WHITELIST: https://demo.careevolution.com,http://127.0.0.1:8081,http://localhost:8081
    ports:
      - "3000:3000"
    volumes:
      - ./src:/srv/src/src
    command: yarn nodemon

  mongo:
    image: mongo:3.6.1
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
